export { default as NavBar } from '../NavBar/NavBar'
export { default as Homepage } from '../Homepage/Homepage'
export { default as News } from '../News/News'
export { default as CryptoDetails } from '../CryptoDetails/CryptoDetails'
export { default as Cryptocurrencies } from '../Cryptocurrencies/Cryptocurrencies'
export { default as Exchanges } from '../Exchanges/Exchanges'